### ISSUE TITLE
Angular Menu

### ISSUE THREAD

**Issue by roblevintennis** [AgnosticUI/agnosticui#140]
This is Angular counterpart to https://github.com/AgnosticUI/agnosticui/issues/88

**Comment by vitale232** [comment]
I'm interested in trying to help out here. Can you help assess my understanding?

It looks like `agnostics-css` is the source of truth for the designs. Additionally, it looks like the `agnostics-css` lib defines opinionated defaults for all of the css properties. These packages could presumably be used standalone in HTML5 and CSS?

Then, it looks like you're re-implementing the component-specific CSS in each frameworks' component library. The framework-specific components take Input Props to determine the exact look and feel desired by the end-user, and simply bind to the correct CSS.

Does that sound about right?

If so, it seems like a reasonable place to begin would to take the `svelte` menu implementation's CSS, bring it over into an Angular component, and start wiring up the inputs?

**Comment by vitale232** [comment]
Here's a little prototype (without keyboard accessibility at this point)

![prototype-no-keyboard](https://user-images.githubusercontent.com/8504254/161433551-2de64eb2-153f-4a46-88dc-92529e36823d.gif)

**Comment by roblevintennis** [comment]
Hey @vitale232 thanks for your interest to help! i'm on my smart phone at the moment so I'll do my best to advise...


￼first look for agnostic-angular/copystyles.js

Since angular uses view encapsulation we should be able to just copy the file wholesale from the CSS package directly over (same as others in that same script).

The you'll run npm run syncStyles from angular directory 

That should copy the menu.css (but if top of my head I think there's also a menuitems.css.

The trickiest thing for me with Angular is the extra :host elements structure that sometimes messes up the CSS targets but I think you can figure out

I would highly recommend looking at the Tabs as a fairly similar example of how the accessible keyboard navigation works.

Lmk if this is enough to get you started and thanks for helping out!

**Comment by roblevintennis** [comment]
The reason we want to have the menu styles copied from the node js script is so we continue to keep any menu CSS changes up to date across frameworks (so copying the styles one time from Svelte is not going to work longer term if that makes sense).

**Comment by vitale232** [comment]
Awesome, thanks for the additional info. I'm up and running with the scripts, and it seems to be going pretty well. I just ran up against the extra Host element in Angular when looking at the rounded menu variant. The border spacing is off by just the tiniest amount from what I can tell (svelte top/angular bottom):

![image](https://user-images.githubusercontent.com/8504254/161540284-f60d6109-385e-4a6e-ac10-1cffd919fc53.png)
![image](https://user-images.githubusercontent.com/8504254/161541336-30fea2cc-062f-4d92-9631-76d70fc22d24.png)

With that said, I think I'm confident I'll be able to contribute something here. I'll probably fork the repo and start reimplementing my prototype. For the `MenuItem`, I may end up using an Angular Directive in lieu of a component so that the buttons end up as direct siblings in the DOM. Directives are essentially "template-less" angular components, that can be attached to any CSS selector. If not a Directive, perhaps a more creative component selector similar to [Angular Material's implementation of a button](https://github.com/angular/components/blob/master/src/material/button/button.ts). Should be fun 🤓

 I'll check in if I have any doubts -- This is my first go with Storybook. Seems nice so far!

**Comment by vitale232** [comment]
Hey @roblevintennis, I've got the repo forked and wanted to start committing some code. I'm running into issues with Husky.

When I run `git commit -m '...'`, I get the following error:

```shell
 bash >  git commit -m 'fix: angular CLI requires minimum Node.js version of either v12.20, v14.15, or v16.10'
yarn run v1.22.17
$ npm run stylelint && npm run build:css && npm run sync:react && npm run sync:angular && npm run sync:vue && npm run sync:svelte

> agnosticui@1.0.3-3 stylelint
> pushd agnostic-css && npm run stylelint && popd

sh: 1: pushd: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
husky - pre-commit hook exited with code 127 (error)
```

Am I missing a setup script? Not quite sure what `pushd` is doing. I get the same error when trying to commit from the repo's root and the `ng` subdir. Should I be using yarn with this project? I've been using npm so far...


**Another question**... Is one of the spec'd behaviors that the first element in the menu gets selected `onOpen`? I noticed that behavior in Svelte when comparing my implementation, and wasn't exactly sure on the correct behavior.

**Comment by roblevintennis** [comment]
Argh I apologize I just heard this here

https://github.com/AgnosticUI/agnosticui/issues/127

I'm not sure if he's fixing it but I will need to one way or another soon. This is a bug on me.

Please just use the no verify workaround I mentioned there. Testing and CICD is not a strength of this project at the moment so let's just shoot for it working well in the Storybook and/or /example Angular kitchen sink app.

Again I appreciate the frustration of encountering the error and I hope you're good using the workaround and I appreciate your efforts!

**Comment by roblevintennis** [comment]
I've mereged #155 thanks @vitale232 🙏  -- the follow up fixes needed are being tracked in this ticket https://github.com/AgnosticUI/agnosticui/issues/181
