### ISSUE TITLE
Vue Typescript Port

### ISSUE THREAD

**Issue by roblevintennis** [AgnosticUI/agnosticui#20]
Convert the Vue 3 implementation to use Typescript

**Motive:** Not being Typescript is a blocker for many modern web developers given the advantages of typing, safety, and IDE autocompletion.

**Approach:** I suspect that the easiest approach to this might be to use the Vite starter to kickstart a new sub-directory package with typescript preconfigured; and then copy the components over one at a time.

___

Related to [Svelte Typescript Port](https://github.com/AgnosticUI/agnosticui/issues/127)

Would be great if someone from the community wanted to take these on! I can help with any AgnosticUI odd conventions and things like `copyStyles`, documentation updates, etc., if these changes are needed.

**Comment by originalwebgurl** [comment]
I wouldn't mind taking on the Vue Typescript port. Should this ticket be split: one for Svelte & Vue?

**Comment by roblevintennis** [comment]
@originalwebgurl You're right. I'll extract out the Svelte one into it's own one now.

Lmk if you'd like to discuss a strategy for porting or if you'd like to just give it a stab that's fine too--thanks!

**Comment by Predeactor** [comment]
I will assume this is the reason why TypeScript is complaining about this: `Could not find a declaration file for module 'agnostic-vue'.`

If anyone has this error too, they can use `noImplicitAny: false` in their `tsconfig.json` to temporarily silence this error until this issue get resolved.

Thank you originalwebgurl for your upcoming work, can't wait to see progress for this package I just learned about today, and that I love already! 🙌

**Comment by originalwebgurl** [comment]
Thanks @roblevintennis . I'll set up my fork and start kicking the tires. I'll update this thread with the proposed work and any questions as they come up.

**Comment by roblevintennis** [comment]
@originalwebgurl I wouldn't object to doing this over several smaller PRs:

1. Create a `agnostic-vue-ts` (temporary package / directory so you can leave the current agnostic-vue)
2. Maybe get the typescript one compiling and add a single component
3. Add one to many more until you've got them all ported
4. Overwrite the agnostic-vue with agnostic-vue-ts (so rename agnostic-vue-ts to agnostic-vue as we do this)

I'm fine if there's an intermediary state where we have an extra "in-progress" package as a result of this. I think the diffs will be smaller and easier to review this way and easier to make small wins. What do you think?

**Comment by originalwebgurl** [comment]
Oh good. I definitely prefer smaller more bite-sized PRs. 

**Some questions**
1. I noticed there are currently no tests in the agnostic-vue project. I prefer TDD and while I doubt I'd have time to add a full Vue test suite for all the components, I could definitely wire all the test runner stuff up and get it started and running at least. Want me to add in a test script (and example and/or docs) for vue?
2. How do you prefer the tasks be listed? Do you want a new project for this, where we can list out the work and anyone can grab a small task as needed or just list them out here under this issue, or something else? 
3. Do you care if I use the Composition API for Vue, or do you want to stick with the Options API? While I personally prefer the Composition API, I'm fine to go either way (Options API is still a more familiar syntax for Vue devs).

**Comment by roblevintennis** [comment]
> I noticed there are currently no tests in the agnostic-vue project. I prefer TDD and while I doubt I'd have time to add a full Vue test suite for all the components, I could definitely wire all the test runner stuff up and get it started and running at least. 
Tests are certainly welcomed! Do you prefer to use unit tests or something like Cypress for this? I'm open to both but I've had a lot of fun using Cypress's composition testing [example](https://github.com/morkro/vue-a11y-dialog/blob/main/src/Demo.spec.ct.js)

> Want me to add in a test script (and example and/or docs) for vue?
Yes on the tests especially since you feel inclined 👍 What do you have in mind for example/docs? I have a "kitchen sink" example where I just sanity check the components in e.g. `agnostic-vue/examples/src/App.vue`. But open to other ideas just lmk.

> How do you prefer the tasks be listed? Do you want a new project for this, where we can list out the work and anyone can grab a small task as needed or just list them out here under this issue, or something else?

I'm fine either way and whichever suits your working style best. I just created a new tag `vue typescript port` so feel free to chunk smaller work and create issues with that tag if that feels more manageable then doing it all here.


Do you care if I use the Composition API for Vue, or do you want to stick with the Options API? While I personally prefer the Composition API, I'm fine to go either way (Options API is still a more familiar syntax for Vue devs).

Composition API is definitely preferred. You'll probably notice a sort of mix and mash of both as I ported Vue 2 options to composition api partially. But if you'd like to replace options with something like `defineOptions` in `setup` etc. etc. I'm definitely a fan.

Some context: The last chunk of work on the Vue package ported it to use Vite + Vue 3 + Composition API (partially as you've noticed). I was so close to just also doing Typescript but chickened out as it was a lot of cognitive overload to learn composition and convert to Vite and all. Glad we're doing this though. Obviously will be great to have stuff typed!

**Comment by originalwebgurl** [comment]
**Tests**
I've been LOVING setting up integration & smoke tests using Cypress on a recent project ❤️ 
I won't have time to go full on cypress specs but can definitely make sure there's a sample cypress test wired up so you can run with it if you like.

I have a lot of feelings and strong opinions about tests. The biggest being that most tests I see in the wild are over complicated and fragile. I'll be keeping my tests lean and focused, very black box / unit testy.

**Docs**
Kitchen sink examples are great, I'd also like to add a super basic example since sometimes the kitchen sink ones can be a bit overwhelming for someone picking up a new framework. I also like to provide a solid test example to encourage others to add their own tests 😄 

**Vue**
I'll go with Composition API then since I'm using it for 2 other projects at the moment (and loving it). 
I'm very used to porting or upgrading live/production projects. If you like we can probably continue the work in the same `agnostic-vue` project folder. I could make that my first PR so you can see if you like that approach first before going too far down that road.

**Comment by roblevintennis** [comment]
## Tests

Cypress is certainly not required and I think you should run with what you have in mind!

## Docs

Agreed. Go for it! The only real docs I have are at https://agnosticui.com/ -- those, btw, are in the `/site` directory and in fact use Vue / Vitepress. See the `agnosticui/site/docs/components/*` for example.

But if you'd like to add some small examples closer to the package I'm all for it 👍 

## Vue

Again, you sound pretty confident. Same folder or not I'll leave to you 💯 I"m very excited that you're using AgnosticUI for 2 projects (and loving it...really! OMG -- that made my day!)

Looking forward to seeing where this goes @originalwebgurl

**Comment by originalwebgurl** [comment]
Sorry for the miscommunication, I meant I was using the composition api in 2 projects. I AM evaluating AgnosticUI for both of them though so 🤞 

I've been having trouble getting the monorepo workspaces working locally though. Reading through https://github.com/AgnosticUI/agnosticui/blob/master/CONTRIBUTING.md#how-it-all-works which references yarn workspaces, but I don't see any `workspaces: [...]` defined in the `package.json` file. Am I missing something here or are the workspaces configured another way? 

I've also run into errors with `pushd` not being found. I suspect this may be an env issue with my Win 11/wsl/ubuntu box setup, since setting the script-setup to use bash instead of sh didn't fix it. I'll keep investigating but thought I'd mention it in case anyone else has run into this and can point me in a better direction.

I'll commit the plumbing work I've started over on my fork and @ you there so I'm not spamming this thread with troubleshooting banter.

**Comment by roblevintennis** [comment]
I think you've likely ran into stale docs which is on me! I'm no longer using `yarn workspaces` and likely those docs need updating. Hoisting became a huge issue and so I removed.

I'll make myself an issue for updating the contributing docs.

In term of the `pushd` issue those were convenience commands from the top-level directory but I would recommend just running the script commands from within the `agnostic-vue/` directory  itself and seeing the `agnostic-vue/package.json` scripts for what's available.

Also I should mention you'll want to install the npm packages within the Vue directory as well (not from top-level as you would if it was still using `workspaces`.)

So ignore anything having to do with `yarn workspaces`.

Not sure if above unblocks you but feel free to wait for updated contributing docs and apologies for those being misleading!

**Comment by originalwebgurl** [comment]
I'll give them a look after work today. Thanks for being so quick to reply!

Also, no apologies necessary. I feel like I should apologize for not mentioning this wasn't currently blocking me since I'm just working inside the `agnostic-vue` sub folder without issues so far. I was just worried my changes could break the parent-level scripts and I wouldn't know.

**Comment by roblevintennis** [comment]
@originalwebgurl in case you've started conversion you should see:
https://github.com/AgnosticUI/agnosticui/issues/134#issuecomment-1077027933

Basically I refactored the `Select` component. Funny enough to use composition api and I made a breaking change emitting now `selected` (was `input`).

**Comment by roblevintennis** [comment]
Any word on this one?

**Comment by roblevintennis** [comment]
Ok I'm assuming interest was lost in this one (no worries!). I've unassigned lmk if I got this wrong.

It looks like a corresponding svelte to typescript port is going so will be interesting to see how that goes

**Comment by roblevintennis** [comment]
I'm finding this issue a bit disappointing. Going to close and create the same damn issue but with a fresh start. Sheesh
